name: WIM project CI

on: [push]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: config.settings
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run Test
        run: pytest